fix gcc 4.7.1 method lookup error by qualifying method calls with "this" pointer
E.g. the error messages for OMCharacterStringPropertyT.h are:
./OMCharacterStringPropertyT.h: In instantiation of ‘void OMCharacterStringProperty<CharacterType>::assign(const CharacterType*) [with CharacterType = wchar_t]’:
OMWideStringProperty.cpp:66:3:   required from here
./OMCharacterStringPropertyT.h:93:3: error: ‘setValue’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
./OMCharacterStringPropertyT.h:93:3: note: declarations in dependent base ‘OMVariableSizeProperty<wchar_t>’ are not found by unqualified lookup
./OMCharacterStringPropertyT.h:93:3: note: use ‘this->setValue’ instead